version: '3.3'
services:
  core: 
    container_name: core
    image: recobook/core:latest
    ports: 
      - 8000:8000
    volumes: 
        - ./src:/app
    environment: 
      SERVICE_AUTH_KEY: "teste"
      SENDGRID_EMAIL: "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"
      SENDGRID_TOKEN: "jadson44.santos@gmail.com"

  dobby: 
    container_name: dobby
    image: recobook/dobby:latest
    ports: 
      - 1993:1993    
    environment: 
      SERVICE_AUTH_KEY: "teste"

  db:
    container_name: database
    image: mysql:5.7
    hostname: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: core
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    
volumes:
  db:
    