version: '3.3'
services:
  core: 
    container_name: core
    build: .
    ports: 
      - 1993:1993
    volumes: 
        - ./src:/app
    environment: 
      SERVICE_AUTH_KEY: "teste"
      CLIENT_SMTP_USERNAME: ""
      CLIENT_SMTP_PASSWORD: ""
      CLIENT_SMTP_EMAIL: ""
      


  dobby: 
    container_name: dobby
    image: recobook/dobby:latest
    ports: 
      - 1993:1993    
    environment: 
      SERVICE_AUTH_KEY: "teste"

  db:
    container_name: database
    image: mysql:5.7
    hostname: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: core
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    
volumes:
  db:
    